### ISSUE TITLE
훈련에 사용한 데이터를 공개해주실 수 있나요?

### ISSUE THREAD

**Issue by insikk** [bluedisk/korean_char_rnn#1]
훈련에 사용하신 데이터가 공개 가능하다면 저를 포함한 많은 사람들이 실험해보는데 매우 유용할 것 같습니다. 혹시 가능할지요?

**Comment by bluedisk** [comment]
저도 공개하고 싶은 마음은 굴뚝 같으나 저작권이 애매한 글들이 다수라서 힘들듯 합니다 ㅠㅜ
